trigger:
- Dev

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/1/s/src/ARMTemplates/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true