trigger:
- Dev

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'ARMTemplates'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true